// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqdwyhgsgbzvizmkmszr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZHd5aGdzZ2J6dml6bWttc3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzQ2MzUsImV4cCI6MjA3MzAxMDYzNX0.XebG3FVYTFbGyz41hATzTqYdR7WqzV1xm_54ynAESUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});